# Generated by Django 4.2.3 on 2023-07-16 08:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130, verbose_name='имя')),
                ('age', models.IntegerField(verbose_name='возраст')),
                ('experience', models.IntegerField(verbose_name='опыт')),
            ],
            options={
                'verbose_name': 'тренер',
                'verbose_name_plural': 'тренеры',
                'ordering': ('-experience',),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'страна',
                'verbose_name_plural': 'страны',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='дата матча')),
                ('time', models.TimeField(verbose_name='время игры')),
            ],
            options={
                'verbose_name': 'матч',
                'verbose_name_plural': 'матчи',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130, verbose_name='имя')),
                ('age', models.IntegerField(verbose_name='возраст')),
                ('position', models.CharField(max_length=130, verbose_name='позиция')),
            ],
            options={
                'verbose_name': 'игрок',
                'verbose_name_plural': 'игроки',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130, unique=True, verbose_name='название')),
                ('city', models.CharField(max_length=130, unique=True, verbose_name='город')),
                ('capacity', models.IntegerField(default=5000, verbose_name='вместимость')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_stadium', to='analytics.country', verbose_name='страна')),
            ],
            options={
                'verbose_name': 'стадион',
                'verbose_name_plural': 'стадионы',
                'ordering': ('capacity',),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='название')),
                ('foundation_year', models.DateField(default=datetime.datetime(2022, 12, 20, 14, 31, 33, 204593), verbose_name='дата создания')),
                ('type_sport', models.CharField(max_length=120, verbose_name='вид спорта')),
                ('coach', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_coach', to='analytics.coach', verbose_name='тренер')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_of_team', to='analytics.country', verbose_name='страна')),
                ('home_stadium', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teams_stadium', to='analytics.stadium', verbose_name='домашний стадион')),
                ('player', models.ManyToManyField(related_name='players_command', to='analytics.player', verbose_name='игрок')),
            ],
            options={
                'verbose_name': 'команда',
                'verbose_name_plural': 'команды',
                'ordering': ('type_sport',),
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130, verbose_name='название')),
                ('date', models.DateField(auto_now_add=True, verbose_name='дата проведения')),
                ('team', models.ManyToManyField(related_name='teams_on_tournament', to='analytics.team', verbose_name='команда')),
            ],
            options={
                'verbose_name': 'турнир',
                'verbose_name_plural': 'турниры',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_scored', models.IntegerField(verbose_name='забито мячей')),
                ('assists', models.IntegerField(verbose_name='сделано асистов')),
                ('hit_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='процент попадания')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics_match_team', to='analytics.match', verbose_name='матч')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_statistic', to='analytics.team', verbose_name='игрок')),
            ],
            options={
                'verbose_name': 'статистика',
                'verbose_name_plural': 'статистика',
                'ordering': ('goals_scored',),
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='позиция')),
                ('ranking_points', models.IntegerField(verbose_name='очки команд')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_ranking', to='analytics.team', verbose_name='команда')),
            ],
            options={
                'verbose_name': 'рейтинг',
                'verbose_name_plural': 'рейтинги',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_away', to='analytics.team', verbose_name='выездная команда'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_home', to='analytics.team', verbose_name='домашняя команда'),
        ),
        migrations.AddField(
            model_name='match',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_on_stadium', to='analytics.stadium', verbose_name='стадион'),
        ),
    ]
