# Generated by Django 4.2.3 on 2023-07-16 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='foundation_year',
            field=models.DateField(default=datetime.datetime(2023, 5, 28, 14, 31, 36, 203001), verbose_name='дата создания'),
        ),
    ]
