# Generated by Django 4.2.3 on 2023-08-20 02:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_team_foundation_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='time',
            field=models.TimeField(auto_now_add=True, verbose_name='время начала игры'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_statistic', to='analytics.team', verbose_name='команда'),
        ),
        migrations.AlterField(
            model_name='team',
            name='foundation_year',
            field=models.DateField(default=datetime.datetime(2023, 5, 24, 8, 32, 48, 92008), verbose_name='дата создания'),
        ),
    ]
