# Generated by Django 4.2.3 on 2023-09-14 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_match_time_alter_statistics_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='избранное'),
        ),
        migrations.AlterField(
            model_name='team',
            name='foundation_year',
            field=models.DateField(default=datetime.datetime(2023, 6, 27, 19, 8, 33, 630955), verbose_name='дата создания'),
        ),
    ]
